### ISSUE TITLE
In ubuntu, src/config/gocash-config.h  should    == GOCash-config.h

### ISSUE THREAD

**Issue by BitexBaycom** [mbambnag/GoCash-Core#1]
zmq/zmqconfig.h:9:34: fatal error: config/GOCash-config.h: No such file or directory
compilation terminated.
Makefile:5013: recipe for target 'zmq/libbitcoin_zmq_a-zmqabstractnotifier.o' failed
make[2]: *** [zmq/libbitcoin_zmq_a-zmqabstractnotifier.o] Error 1
make[2]: Leaving directory '/data/GoCash-Core-v.1.1.1.5/src'
Makefile:7564: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/data/GoCash-Core-v.1.1.1.5/src'
Makefile:611: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

In ubuntu, src/config/gocash-config.h  should    == GOCash-config.h

**Comment by mbambnag** [comment]
it's there right now
